[package]
name = "pgfault-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true
bytes.workspace = true
socket2.workspace = true
tracing.workspace = true
pgfault-wire = { path = "../pgfault-wire" }
pgfault-events = { path = "../pgfault-events" }
pgfault-state = { path = "../pgfault-state" }
pgfault-scenario = { path = "../pgfault-scenario" }
pgfault-trace = { path = "../pgfault-trace" }

humantime.workspace = true
tokio-rustls.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
webpki-roots.workspace = true

[dev-dependencies]
tempfile = "3"
tokio-postgres = "0.7"
